services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    networks:
      - nginx_proxy
    ports:
      - "5300:5300/tcp"
      - "5300:5300/udp"
      # web ports go only to NPM, not exposed directly
    environment:
      TZ: 'Etc/UTC'
      WEBPASSWORD: 'changeme'       # change this 
      VIRTUAL_HOST: 'your_host_ip'   # ubuntu_server_ip 
      VIRTUAL_PORT: 80
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN

networks:
  nginx_proxy:
    external: true
